# New Set Constructor
#
# This function creates \code{LEV_sets} object
new_sets <- function(athlete,
                     visit,
                     V0,
                     L0,
                     v1RM,
                     `1RM`,
                     visit_1RM,
                     prescription_1RM,
                     load_increment,
                     set,
                     load_index,
                     load,
                     set_V0,
                     set_L0,
                     set_1RM,
                     RTF,
                     nRM,
                     rep,
                     rep_V0,
                     rep_L0,
                     rep_1RM,
                     failed_rep,
                     true_rep_velocity,
                     biological_rep_velocity,
                     measured_rep_velocity,
                     RIR,
                     `%MNR`,
                     best_measured_rep_velocity,
                     VL,
                     `%VL`,
                     VR) {
  sets <- dplyr::tibble(
    athlete = athlete,
    visit = visit,
    V0 = V0,
    L0 = L0,
    v1RM = v1RM,
    `1RM` = `1RM`,
    visit_1RM = visit_1RM,
    prescription_1RM = prescription_1RM,
    load_increment = load_increment,
    set = set,
    load_index = factor(load_index),
    load = load,
    set_V0 = set_V0,
    set_L0 = set_L0,
    set_1RM = set_1RM,
    RTF = RTF,
    nRM = nRM,
    rep = rep,
    rep_V0 = rep_V0,
    rep_L0 = rep_L0,
    rep_1RM = rep_1RM,
    failed_rep = failed_rep,
    true_rep_velocity = true_rep_velocity,
    biological_rep_velocity = biological_rep_velocity,
    measured_rep_velocity = measured_rep_velocity,
    RIR = RIR,
    `%MNR` = `%MNR`,
    best_measured_rep_velocity = best_measured_rep_velocity,
    VL = VL,
    `%VL` = `%VL`,
    VR = VR
  )

  class(sets) <- "LEV_sets"
  return(sets)
}
