# New Sets Summary Constructor
#
# This function creates \code{LEV_summary} object
new_summary <- function(athlete,
                        visit,
                        V0,
                        L0,
                        v1RM,
                        `1RM`,
                        visit_1RM,
                        prescription_1RM,
                        set,
                        set_V0,
                        set_L0,
                        load_type,
                        load_index,
                        load_perc,
                        load_perc_adj,
                        set_to_failure,
                        target_reps,
                        load,
                        nRM,
                        reps_done,
                        RIR,
                        `%MNR`,
                        est_RIR,
                        est_nRM,
                        `est_%MNR`,
                        first_true_rep_velocity,
                        last_true_rep_velocity,
                        first_manifested_rep_velocity,
                        last_manifested_rep_velocity,
                        first_measured_rep_velocity,
                        last_measured_rep_velocity,
                        best_measured_rep_velocity,
                        VL,
                        `%VL`,
                        VR) {
  summary <- dplyr::tibble(
    athlete = athlete,
    visit = visit,
    V0 = V0,
    L0 = L0,
    v1RM = v1RM,
    `1RM` = `1RM`,
    visit_1RM = visit_1RM,
    prescription_1RM = prescription_1RM,
    set = set,
    set_V0 = set_V0,
    set_L0 = set_L0,
    load_type = load_type,
    load_index = load_index,
    load_perc = load_perc,
    load_perc_adj = load_perc_adj,
    set_to_failure = set_to_failure,
    target_reps = target_reps,
    load = load,
    nRM = nRM,
    reps_done = reps_done,
    RIR = RIR,
    `%MNR` = `%MNR`,
    est_RIR = est_RIR,
    est_nRM = est_nRM,
    `est_%MNR` = `est_%MNR`,
    first_true_rep_velocity = first_true_rep_velocity,
    last_true_rep_velocity = last_true_rep_velocity,
    first_manifested_rep_velocity = first_manifested_rep_velocity,
    last_manifested_rep_velocity = last_manifested_rep_velocity,
    first_measured_rep_velocity = first_measured_rep_velocity,
    last_measured_rep_velocity = last_measured_rep_velocity,
    best_measured_rep_velocity = best_measured_rep_velocity,
    VL = VL,
    `%VL` = `%VL`,
    VR = VR
  )

  class(summary) <- "LEV_summary"
  return(summary)
}
